/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Reservations: () => import('#controllers/reservations_controller'),
  Rooms: () => import('#controllers/rooms_controller'),
  Seats: () => import('#controllers/seats_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
}
