/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthSchema extends BaseModel {
  static $columns = ['id', 'createdAt', 'updatedAt'] as const
  $columns = AuthSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReservationSchema extends BaseModel {
  static $columns = ['id', 'sessionId', 'seatId', 'user', 'status', 'createdAt', 'updatedAt'] as const
  $columns = ReservationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sessionId: number
  @column()
  declare seatId: number
  @column()
  declare user: string
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoomSchema extends BaseModel {
  static $columns = ['id', 'name', 'seats', 'createdAt', 'updatedAt'] as const
  $columns = RoomSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare seats: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SeatSchema extends BaseModel {
  static $columns = ['id', 'roomId', 'seatNumber', 'seatRow', 'createdAt', 'updatedAt'] as const
  $columns = SeatSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roomId: number
  @column()
  declare seatNumber: number
  @column()
  declare seatRow: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SessionSchema extends BaseModel {
  static $columns = ['id', 'roomId', 'movieName', 'sessionDate', 'sessionTime', 'status', 'createdAt', 'updatedAt'] as const
  $columns = SessionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roomId: number
  @column()
  declare movieName: string
  @column.date()
  declare sessionDate: DateTime
  @column()
  declare sessionTime: string
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
